### ISSUE TITLE
Script Fails To Run

### ISSUE THREAD

**Issue by r3dlobst3r** [l3uddz/ss-tvirl#10]
I get this error:
  File "./ss-tvirl.py", line 37
SyntaxError: Non-ASCII character '\xe2' in file ./ss-tvirl.py on line 37, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Any help is appriciated

**Comment by l3uddz** [comment]
think this is a formatting error. works fine here. try replacing the ss-tvirl.py with the one off github and replace the settings with your information.
