### ISSUE TITLE
Internal Runtime Error

### ISSUE THREAD

**Issue by Greene48** [l3uddz/ss-tvirl#12]
I ran the script successfully, added the playlist and epg links to TVirl successfully, and I can open up Live Channels and browse the guide, but when I try to watch a channel I get a black screen and the following message:

> Internal runtime error
> Error: Connection Refused

Any ideas?

edit: I tried restarting the script and now I'm getting a connection error there as well.

> ConnectionError: HTTPConnectionPool(host='fast-guide.smoothstreams.tv', port=80): Max retries exceeded with url: /feed.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x8a46aac>: Failed to establish a new connection: [Errno 110] Connection timed out',))

edit2: The script seems to start sometimes and not others. But either way, I still get the runtime error on the Live Channels app.

**Comment by Greene48** [comment]
So I managed to get this working. I needed to make the address in the SERVER_HOST setting be the local IP of the server I had it running on. So my settings look like this:

```
SERVER_IP = "0.0.0.0"
SERVER_HOST = "http://192.168.2.16:" + str(LISTEN_PORT)
```

Note, this is just to access it locally, not publicly.

**Comment by l3uddz** [comment]
Yep, the server host is used in the generated playlist that tvirl uses to ask ss-tvirl to redirect it to the channel. If you want to use it externally too, change the local IP to a dynamic DNS and forward the port to the machine running it.

**Comment by Greene48** [comment]
Cool, thanks. I do have a dynamic DNS set up. But what would be the use case for accessing it externally? I guess if you wanted to set up on a friends Android TV?

**Comment by l3uddz** [comment]
yeah, or so you can run it on a server and access it while on the go etc using some kind of iptv mobile app.

**Comment by Greene48** [comment]
So I set SERVER_HOST to:

`SERVER_HOST = "http://mydomain.com:" + str(LISTEN_PORT)`

This works great for accessing externally, like you said. But now the handshake fails locally, because I guess my router doesn't support loopback connections (I can't use the WAN IP to access that computer from inside the network, only the LAN IP works). Is there a way to set this up so that the handshake will succeed both locally and externally?

**Comment by dbowles1975** [comment]
Use a static DNS entry in your router that redirects your DDNS back to the IP of the machine running the script.
