### ISSUE TITLE
Fog guide data no longer available

### ISSUE THREAD

**Issue by GvnCampbell** [l3uddz/ss-tvirl#14]
I noticed the fog guide data link is no longer available, however you can now use the link directly from smoothstreams and get the same data.

old link: https://sstv.fog.pt/epg/xmltv5.xml.gz
new link: https://guide.smoothstreams.tv/altepg/xmltv5.xml.gz

**Comment by l3uddz** [comment]
Thanks for bringing to my attention, have made that change and everything appears to be functioning as expected.
