### ISSUE TITLE
500 error for playlist

### ISSUE THREAD

**Issue by tenzone** [l3uddz/ss-tvirl#2]
This was working great until yesterday.   I tried to connect to it to test an iphone app, and it got zero channels..   i went to the web browser to see if it tried to download the playlist file, and got a 500 internal server error.  something is still working because the epg.xml link still re-directs to the fog.pt.feed.xml link

i restarted the service, restarted the server, and restarted the hypervisor the vm lives on, pulled the latest commit from GH.   im not sure whats going on... the log file shows:

`2017-09-10 09:55:40,315 - INFO       - ss-tvirl   -  bridge                   - All channels playlist was requested by 192.168.0.8
2017-09-10 09:55:40,395 - DEBUG      - ss-tvirl   -  get_playlist             - Retrieved fogs SmoothStreams.m3u8
2017-09-10 09:55:40,395 - DEBUG      - ss-tvirl   -  remap_playlist           - Remapping playlist from fog`

but looking at earlier successful times its not showing these lines:
`2017-09-08 15:44:12,031 - INFO       - ss-tvirl   -  remap_playlist           - Built remapped playlist
2017-09-08 15:44:12,031 - INFO       - ss-tvirl   -  bridge                   - Sending playlist to 192.168.0.8`

let me know if theres anything you can see or if theres any other logs you might need from me etc...

thanks

**Comment by dbowles1975** [comment]
Yeah, the JSON the playlist is pulled from is no longer valid so it can't pull it in to remap it. You might want to follow here:

https://smoothstreams.tv/board/index.php?topic=1617.105

**Comment by l3uddz** [comment]
should be fixed - just tested on my setup again (havent watched since yesterday!)

**Comment by l3uddz** [comment]
P.S. You will need to clear channels from within tvirl and rescan it.

**Comment by tenzone** [comment]
thanks   ill pull the file and test soon when im back in front of the computer

**Comment by tenzone** [comment]
thanks   fixed on my tests   appreciate it!!

**Comment by tenzone** [comment]
i think i spoke too soon.   i was able to not get the 500 error, however when i load my live channels, or try on my app to play the playlist, i get "unexpected video not playable" or "channel unavailable" messages

**Comment by l3uddz** [comment]
did you do Clean all first then Reload current playlist?

**Comment by tenzone** [comment]
on my iphone (GSE TV) app i removed the playlist then restarted the app, and re-entered the playlist... On TV IRL i did not do a full clean, i just reloaded...  am cleaning right now and will upadate on what happens

**Comment by l3uddz** [comment]
ok. should be working fine. am watching it on live channels now, however i did need todo the clean all first due to slight changes to playlist

**Comment by SubNoizey** [comment]
This is more compute intensive right? I'm running it on a Pi3 and I think tvirl is timing out before my pi can generate the playlist and send it on.

Anyone have it running on a pi?

**Comment by l3uddz** [comment]
It's definitely more cpu intensive. I will see if there's anyway I can speed it up. I expect I can make improvements to the XML parsing.

**Comment by l3uddz** [comment]
@SubNoizey made a slight change that should help a little bit, let me know if thats any better. I dont have an RPi to test on.

**Comment by SubNoizey** [comment]
Hitting it from my pc it actually feels slower than the version from earlier today. Still gives a timeout in TVirl. 
Thanks for trying 👍

**Comment by tenzone** [comment]
did another pull this afternoon, and it i now working via VLC, and iphone app (gse iptv) i suspect it will work with tvirl once i get home

**Comment by tsqrd** [comment]
Tvirl is only waiting around 10 seconds for the playlist to load and then times out.  The script is taking around 20 seconds now to return the playlist file.

```
2017-09-11 18:55:15,328 - INFO       - ss-tvirl   -  bridge                   - All channels playlist was requested by 192.168.86.45
2017-09-11 18:55:15,329 - DEBUG      - ss-tvirl   -  build_playlist           - Loading feed from SmoothStreams
2017-09-11 18:55:16,777 - DEBUG      - ss-tvirl   -  build_channel_map        - Loading epg from fog
2017-09-11 18:55:36,803 - DEBUG      - ss-tvirl   -  build_channel_map        - Built channel map with 155 channels
2017-09-11 18:55:36,808 - INFO       - ss-tvirl   -  build_playlist           - Built playlist
2017-09-11 18:55:36,808 - INFO       - ss-tvirl   -  bridge                   - Sending playlist to 192.168.86.45



2017-09-11 18:58:38,207 - INFO       - ss-tvirl   -  bridge                   - All channels playlist was requested by 192.168.86.45
2017-09-11 18:58:38,208 - DEBUG      - ss-tvirl   -  build_playlist           - Loading feed from SmoothStreams
2017-09-11 18:58:39,650 - DEBUG      - ss-tvirl   -  build_channel_map        - Loading epg from fog
2017-09-11 18:58:56,825 - DEBUG      - ss-tvirl   -  build_channel_map        - Built channel map with 155 channels
2017-09-11 18:58:56,829 - INFO       - ss-tvirl   -  build_playlist           - Built playlist
2017-09-11 18:58:56,830 - INFO       - ss-tvirl   -  bridge                   - Sending playlist to 192.168.86.45

```

**Comment by l3uddz** [comment]
I will make another change and post here which should solve this for you guys.

**Comment by l3uddz** [comment]
I have made a change that should solve this issue once and for all, hopefully!

**Comment by SubNoizey** [comment]
It's throwing this when I tail status.log

Exception while building initial playlist: 
Traceback (most recent call last):
  File "/var/www/html/sstv/ss-tvirl.py", line 237, in <module>
    playlist = build_playlist()
  File "/var/www/html/sstv/ss-tvirl.py", line 155, in build_playlist
    feed = loads(urlopen(url).read().decode("utf-8"))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Is there a new requirement ?

**Comment by l3uddz** [comment]
No there should be no new requirement. Is this being ran on an ovh server by any chance ?

**Comment by vcr413** [comment]
I am also getting the errors:

Exception while building initial playlist:
Traceback (most recent call last):
File "/var/www/html/sstv/ss-tvirl.py", line 237, in 
playlist = build_playlist()
File "/var/www/html/sstv/ss-tvirl.py", line 155, in build_playlist
feed = loads(urlopen(url).read().decode("utf-8"))
File "/usr/lib/python2.7/json/init.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Running the server on a raspberry pi 3 with raspbian

**Comment by l3uddz** [comment]
It's looking like its failing to decode the feed.json from smoothstreams.tv. I just ran on my PC and server, without issue.. 
On your system, if you do ```wget http://fast-guide.smoothstreams.tv/feed.json``` can you confirm its a valid json file?

**Comment by vcr413** [comment]
I actually just re-ran the script and received no errors and it's working as it should. I didn't make changes, weird.

**Comment by dbowles1975** [comment]
I get the same error occasionally but it seems to work just fine regardless. Running on Windows 10 Home.

**Comment by vcr413** [comment]
In Live channels after about 4 channel requests to the server, i get 403 error video unexpectedly unavailable. Looking at the log, it appears that it is getting the request for the channel but i still am receiving that error

**Comment by 007reddit** [comment]
I am still getting same error on pi3 as SubNoizey and 500 error when i try to access playlist

**Comment by l3uddz** [comment]
@vcr413 once you see the channel has been requested, this means the client has been forwarded to smoothstreams, from this point on, i have no control as you are streaming directly with smoothstreams, perhaps try changing server, will help?

@007reddit its a little hard to test this, as I do not have an RPi3 (script works perfectly here and on my server). Please try the wget I said above and check the downloaded file, does it look like a valid json file, or is it empty? I know that OVH is banned by smoothstreams so will not work there.

**Comment by 007reddit** [comment]
looks valid. I guess i will continue playing around with it and try to figure out what's going on.


{"1":{"channel_id":"1","name":"01 - ESPNNews","img":"https:\/\/guide.smoothstreams.tv\/assets\/images\/channels\/1.png","items":[{"id":"210323","network":"","network_id":"5933","network_switched":"0","name":"MLB: Cincinnati Reds at St. Louis Cardinals","description":"MLB: Cincinnati Reds at St. Louis Cardinals","time":

**Comment by l3uddz** [comment]
@007reddit I have made a change to use the requests module. Please try this and let me know if it helps. You will need to make sure you have requests module installed, by installing the requirements.txt again.

**Comment by SubNoizey** [comment]
works for me!

appreciate it!!!

**Comment by l3uddz** [comment]
glad to hear it

**Comment by 007reddit** [comment]
Works perfectly now. Thanks.

Heads up - had to clear cache and data on both tvirl and Live TV before it worked on Live TV again.
