### ISSUE TITLE
Adding other streams for channels SS got rid of

### ISSUE THREAD

**Issue by tenzone** [l3uddz/ss-tvirl#8]
not quite a issue, but more of a request.  I posted on the Live channel thread on the board but thought it might fit here since I use this script and you maintain it. If you feel like this is the wrong place for this request please delete it and accept my apologies:

On the smoothstreams subreddit someone was talking about missing MSNBC. I do as well.   another poster posted a stream for a msnbc live stream:
http://tvemsnbc-lh.akamaihd.net/i/nbcmsnbc_1@122532/master.m3u8 as well as the following for adding to a playlist: 
```

#EXTM3U
#EXTINF:-1 tvg-id="MSNBC.us" tvg-name="MSNBC" tvg-logo="http://www.siriusxm.com/cmds/displayLogo?key=8367&imageType=16&.png" group-title="World News" parent-code="",MSNBC
http://tvemsnbc-lh.akamaihd.net/i/nbcmsnbc_1@122532/master.m3u8

```
could there be a way to append this to the script and use one of the empty channels, or add another one on the output playlist to include this channel?

otherwise, i guess i could use another app, like cumulus and add other channels to another playlist, but it would be much tidier to have it all in one place.

**Comment by l3uddz** [comment]
Will take a look at this when I have a free moment.
