### ISSUE TITLE
Question about SERVER_HOST

### ISSUE THREAD

**Issue by dbowles1975** [l3uddz/ss-tvirl#9]
I've had this up and running for awhile now but just decided to make it accessible outside the network. I'm listening on 0.0.0.0 and I have port forwarding set up and working. I can access the playlist and epg from outside my network. My issue is with the SERVER_HOST parameter. Reading the set up instructions I can't make sense of what to put here to make it work outside of my network. Right now I have it set to the IP of the machine the script is running on. 

`SERVER_HOST = "http://192.168.1.3:" + str(LISTEN_PORT)`

If I change it to anything else I can no longer play anything inside my network. Could you help me figure out what I'm doing wrong? Thanks.

**Comment by l3uddz** [comment]
SERVER_HOST is used when building the playlist. each channel must "handshake" if you will with the script, so it can redirect directly to smoothstreams for streaming. 

If you are having issues inside network, it is likely failing to receive connections, perhaps the port is not being forwarded to the machine running the script in your router settings?

**Comment by dbowles1975** [comment]
The port is forwarded to the machine running the script. I can pull up the m3u8 and epg.xml from outside my network. The problem is that nothing plays from outside the network.  From within the network everything works perfectly.

**Comment by l3uddz** [comment]
Hmm. I'm really not sure what to suggest. Port forwarding was the only thing that popped to mind. 
I'm using the script on a dedicated server and have no problems streaming.

What are you using as the SERVER_HOST when you try to play from outside the network?

**Comment by dbowles1975** [comment]
It's in my original post:

`SERVER_HOST = "http://192.168.1.3:" + str(LISTEN_PORT)`

That's the IP of the machine the script runs on. Like I said I'm sure port forwarding is working because I can enter mydomainname.org:6752/sstv/playlist.m3u8 from outside the network and VLC will open the m3u8 but then I get "VLC is unable to open the MRL 'http://192.168.1.3:6752/sstv/playlist.m3u8?channel=51'. Check the log for details."

**Comment by l3uddz** [comment]
That makes sense then, because outside the network, its trying to connect to the network ip, which ofcourse wont be accessible outside your network. Change the IP in SERVER_HOST to your domain and try that. Let me know if that solves it.

**Comment by dbowles1975** [comment]
Yeah, replacing the local IP with DDNS did it. I'm not sure why I didn't think of that before. It seems so obvious now.
